
ghost-spawn-point:
  x: 0
  y: 0
  z: 0
  world: "world"

ghost-message: "Вы цалкам вычарпалі ўсе запасы чалавечнасці і ператварыліся ў прывіда. Вы больш не маеце магчымасці ўзаемадзейнічаць з асяроддзем, а маеце толькі магчымасць адчуваць пустыню паміж старым светам і новым."
humanity-message: "Вы зноў чалавек. Пасля мноства дзён у стане прывіда, вы можаце адчуць цяпло сонца на вашай скуры і пачуць пульс вашага сэрца. Вы цяпер маеце магчымасць ўзаемадзейнічаць з асяроддзем, а ваша сувязь са старым светам аднавілася."