name: GhostBan
version: '${version}'
main: by.siarhiejbahdaniec.ghostban.GhostBan
api-version: '1.20'
depend: [LuckPerms]
permissions:
  ghostban.humanity:
    description: Дае гульцу чалавечнасць, без якой ён не можа ўзаемадзейнічаць з асяроддзем і губляе чалавечае аблічча.
